{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext sql\n",
    "\n",
    "import boto3\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## STEP 1: Get the params of the created redshift cluster \n",
    "- We need:\n",
    "    - The redshift cluster <font color='red'>endpoint</font>\n",
    "    - The <font color='red'>IAM role ARN</font> that give access to Redshift to read from S3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "import configparser\n",
    "config = configparser.ConfigParser()\n",
    "config.read_file(open('dwh.cfg'))\n",
    "\n",
    "KEY                    = config.get('AWS','KEY')\n",
    "SECRET                 = config.get('AWS','SECRET')\n",
    "\n",
    "DWH_DB                 = config.get(\"DWH\",\"DWH_DB\")\n",
    "DWH_DB_USER            = config.get(\"DWH\",\"DWH_DB_USER\")\n",
    "DWH_DB_PASSWORD        = config.get(\"DWH\",\"DWH_DB_PASSWORD\")\n",
    "DWH_PORT               = config.get(\"DWH\",\"DWH_PORT\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "DWH_ENDPOINT    = \"redshift-cluster-1.ceied2kgdafs.us-east-1.redshift.amazonaws.com\"\n",
    "DWH_ROLE_ARN    = \"arn:aws:iam::472183003754:role/redshift-role\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## STEP 2: Connect to the Redshift Cluster"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n",
      "    self.dialect.do_execute(\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "psycopg2.errors.UndefinedObject: unrecognized configuration parameter \"standard_conforming_strings\"\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sql/magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sql/connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sql/connection.py\", line 55, in __init__\n",
      "    self.internal_connection = engine.connect()\n",
      "                               ^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3278, in connect\n",
      "    return self._connection_cls(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 146, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "                             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 3302, in raw_connection\n",
      "    return self.pool.connect()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "          ^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/pool/base.py\", line 914, in __connect\n",
      "    )._exec_w_sync_on_first_run(self.dbapi_connection, self)\n",
      "      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/event/attr.py\", line 483, in _exec_w_sync_on_first_run\n",
      "    self(*args, **kw)\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/event/attr.py\", line 497, in __call__\n",
      "    fn(*args, **kw)\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py\", line 1912, in go\n",
      "    return once_fn(*arg, **kw)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/create.py\", line 749, in first_connect\n",
      "    dialect.initialize(c)\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py\", line 677, in initialize\n",
      "    super().initialize(connection)\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/base.py\", line 3120, in initialize\n",
      "    self._set_backslash_escapes(connection)\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/base.py\", line 5004, in _set_backslash_escapes\n",
      "    std_string = connection.exec_driver_sql(\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1779, in exec_driver_sql\n",
      "    ret = self._execute_context(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1846, in _execute_context\n",
      "    return self._exec_single_context(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1986, in _exec_single_context\n",
      "    self._handle_dbapi_exception(\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 2355, in _handle_dbapi_exception\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n",
      "    self.dialect.do_execute(\n",
      "  File \"/Users/ahmetcicekci/Desktop/projects/udacity-data-eng/data-warehouse-aws/env-warehouse-aws-2/lib/python3.12/site-packages/sqlalchemy/engine/default.py\", line 941, in do_execute\n",
      "    cursor.execute(statement, parameters)\n",
      "sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) unrecognized configuration parameter \"standard_conforming_strings\"\n",
      "\n",
      "[SQL: show standard_conforming_strings]\n",
      "(Background on this error at: https://sqlalche.me/e/20/f405)\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "conn_string=\"postgresql://{}:{}@{}:{}/{}\".format(DWH_DB_USER, DWH_DB_PASSWORD, DWH_ENDPOINT, DWH_PORT, DWH_DB)\n",
    "%sql $conn_string\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/full/')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/full/full.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00000-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00001-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00002-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00003-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00004-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00005-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00006-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00007-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00008-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n",
      "s3.ObjectSummary(bucket_name='udacity-labs', key='tickets/split/part-00009-d33afb94-b8af-407d-abd5-59c0ee8f5ee8-c000.csv.gz')\n"
     ]
    }
   ],
   "source": [
    "s3 = boto3.resource('s3', region_name=\"us-east-1\", aws_access_key_id=KEY, aws_secret_access_key=SECRET)\n",
    "\n",
    "bucket = s3.Bucket(\"udacity-labs\") # public bucket\n",
    "for obj in bucket.objects.filter(Prefix=\"tickets\"):\n",
    "    print(obj)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env-warehouse-aws",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
